source=$HOME/.config/hypr/hyprland/general.conf
source=$HOME/.config/hypr/hyprland/keybinds.conf
source=$HOME/.config/hypr/hyprland/env.conf
source=$HOME/.config/hypr/hyprland/execs.conf
source=$HOME/.config/hypr/hyprland/colors.conf
# source=$HOME/.config/hypr/hyprland/rules-layers.conf
# source=$HOME/.config/hypr/hyprland/rules-windows.conf

