[default]
duration = "1m"
mode = "fit"
transition-time = 300
queue-size = 5

[any]
path = "/home/jagteshver/images/backgrounds/Wallpapers/Landscape"
# path = "/home/jagteshver/images/backgrounds/AnimeWallpapers/Landscape"
# path = "/home/jagteshver/images/backgrounds/NSFW-Wallpapers/Landscape"
