[config.wallpaper]
# command = "swww"
# arguments = ["img", "--transition-type", "center"]
# set = false # set not working
command = "sleep"
arguments = ["0", ";"]

[templates.alacritty]
input_path = '~/.config/matugen/templates/alacritty.toml'
output_path = '~/.config/alacritty/theme.toml'
