[Palette]
Window={{ colors.surface.default.hex }}
WindowText={{ colors.on_surface.default.hex }}
Base={{ colors.surface_container.default.hex }}
AlternateBase={{ colors.surface_variant.default.hex }}
Text={{ colors.on_surface.default.hex }}
Button={{ colors.surface_container.default.hex }}
ButtonText={{ colors.on_surface.default.hex }}
BrightText={{ colors.on_error.default.hex }}
Highlight={{ colors.primary_container.default.hex }}
HighlightedText={{ colors.on_primary_container.default.hex }}
Link={{ colors.primary.default.hex }}
LinkVisited={{ colors.tertiary.default.hex }}
ToolTipBase={{ colors.surface.default.hex }}
ToolTipText={{ colors.on_surface.default.hex }}
PlaceholderText={{ colors.on_surface_variant.default.hex }}

[Colors]
background={{ colors.surface.default.hex }}
foreground={{ colors.on_surface.default.hex }}
primary={{ colors.primary.default.hex }}
secondary={{ colors.secondary.default.hex }}
accent={{ colors.tertiary.default.hex }}
negative={{ colors.error.default.hex }}
disabled={{ colors.on_surface_variant.default.hex }}

[General]
active_color_scheme=matugen
color_scheme_path=
