source=hyprlock/theme.conf

$font_fam = 'MonaspiceXe NFP'

# BACKGROUND
background {
  monitor =
  path = $wallpaper
  blur_passes = 1
  noise = 0.2
  color = $primary
}

source=hyprlock/login-card.conf
source=hyprlock/clock-card.conf
source=hyprlock/profile-card.conf
source=hyprlock/sys-media-card.conf
