# CLOCK CARD
shape {
    monitor =
    size = 500, 160
    color = $surface_50_opacity
    rounding = 25
    position = -200, -140
    halign = center
    valign = center
    zindex = 1
}

label {
    monitor =
    text = cmd[update:1000] date +"<b>%H:%M</b>"
    color = $on_surface
    font_size = 72
    font_family = $font_fam
    position = -200, -125
    halign = center
    valign = center
    zindex = 2
}

label {
    monitor =
    text = cmd[update:1000] uptime -p | sed -e 's/up /      Uptime: /' -e 's/ hours, /H /' -e 's/ minutes/M /'
    color = $on_surface_2
    font_size = 14
    font_family = $font_fam
    position = -260, -195
    halign = center
    valign = center
    zindex = 2
}
