# LOGIN CARD
shape {
    monitor =
    size = 360, 380
    color = $surface_50_opacity
    rounding = 25
    border_size = 0
    position = -200, 160
    halign = center
    valign = center
    zindex = 1
}

label {
    monitor =
    text = cmd[update:1000] hostname
    color = $on_surface
    font_size = 14
    font_family = $font_fam
    position = -200, 300
    halign = center
    valign = center
    zindex = 2
}

label {
    monitor =
    text = Log in
    color = $on_surface
    font_size = 42
    font_family = $font_fam
    position = -200, 240
    halign = center
    valign = center
    zindex = 2
}

# Username Display
shape {
    monitor =
    size = 320, 70
    color = $primary
    rounding = 20
    position = -200, 130
    halign = center
    valign = center
    zindex = 2
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$USER</b>"
    color = $on_primary
    font_size = 18
    font_family = $font_fam
    position = -200, 130
    halign = center
    valign = center
    zindex = 3
}

# Password Input
input-field {
    monitor =
    size = 320, 70
    outline_thickness = 0
    dots_size = 0.25
    dots_spacing = 0.4
    dots_center = false
    outer_color = $outline
    inner_color = $primary
    font_color = $on_primary
    fade_on_empty = false
    placeholder_text = password
    hide_input = false
    rounding = 20
    position = -200, 40
    halign = center
    valign = center
    check_color = $primary
    check_text = Checking Password
    fail_color = $error
    zindex = 2
}
