# PROFILE CARD (Blurred)
shape {
    monitor =
    size = 360, 350
    color = $surface_50_opacity
    rounding = 25
    position = 200, 175
    halign = center
    valign = center
    zindex = 1
}

image {
    monitor =
    path = ~/images/me
    size = 120
    rounding = 20
    border_size = 4
    border_color = $primary
    position = 110, 240
    halign = center
    valign = center
    zindex = 2
}

label {
    monitor =
    text = cmd[update:1000] echo "<b>$(date +"%a" | tr '[:lower:]' '[:upper:]')</b>"
    color = $on_surface
    font_size = 38
    font_family = $font_fam
    position = 270, 265
    halign = center
    valign = center
    zindex = 2
}

label {
    monitor =
    text = cmd[update:1000] date +"%d %B, %Y"
    color = $on_surface_2
    font_size = 14
    font_family = $font_fam
    position = 270, 210
    halign = center
    valign = center
    zindex = 11
}

