[ids]
*

[main]

capslock = overload(nav, esc)
space = overload(sym, space)
enter = overload(num, enter)

a = overload(control, a)
s = overload(alt, s)
d = overload(meta, d)
f = overload(shift, f)

j = overload(shift, j)
k = overload(meta, k)
l = overload(alt, l)
; = overload(control, ;)

[nav]

h = left
j = down
k = up
l = right

u = home
i = pageup
o = end
p = pagedown

n = C-left
m = C-right

[sym]

j = (
k = )
u = [
i = ]
n = {
m = }

7 = !
8 = @
9 = #

[num]

u = 7
i = 8
o = 9

j = 4
k = 5
l = 6

m = 1
, = 2
. = 3

space = 0
