return {
  -- {
  --   'smallcloudai/refact-neovim',
  --   lazy = false,
  --   config = function()
  --     require('refact-neovim').setup {
  --       address_url = 'http://127.0.0.1:8008',
  --       api_key = 'null',
  --     }
  --   end,
  -- },
  -- Remove the `use` here if you're using folke/lazy.nvim.
  -- {
  --   'Exafunction/codeium.vim',
  --   config = function()
  --     -- Change '<C-g>' here to any keycode you like.
  --     vim.keymap.set('i', '<C-g>', function()
  --       return vim.fn['codeium#Accept']()
  --     end, { expr = true, silent = true })
  --     vim.keymap.set('i', '<c-;>', function()
  --       return vim.fn['codeium#CycleCompletions'](1)
  --     end, { expr = true, silent = true })
  --     vim.keymap.set('i', '<c-,>', function()
  --       return vim.fn['codeium#CycleCompletions'](-1)
  --     end, { expr = true, silent = true })
  --     vim.keymap.set('i', '<c-x>', function()
  --       return vim.fn['codeium#Clear']()
  --     end, { expr = true, silent = true })
  --   end,
  -- },
}
